### ISSUE TITLE
any guide to setup the dataset for ready to training?

### ISSUE THREAD

**Issue by SeekPoint** [ale3otik/paraphrases-generator#2]
mldl@ub1604:~/ub16_prj/paraphrases-generator$ python3 train.py 
ALL: train: 0, test: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'question1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 51, in <module>
    batch_loader = BatchLoader(datasets=datasets)
  File "/home/mldl/ub16_prj/paraphrases-generator/utils/batch_loader.py", line 61, in __init__
    self.build_vocab(sentences)
  File "/home/mldl/ub16_prj/paraphrases-generator/utils/batch_loader.py", line 265, in build_vocab
    sentences = self.get_sentences_from_data()
  File "/home/mldl/ub16_prj/paraphrases-generator/utils/batch_loader.py", line 250, in get_sentences_from_data
    sentences += list(df['question1'].values) + list(df['question2'].values)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'question1'
mldl@ub1604:~/ub16_prj/paraphrases-generator$

**Comment by ale3otik** [comment]
https://github.com/ale3otik/paraphrases-generator/blob/master/quora_data_process.ipynb
Here is the train/test split generation from original dataset. 

In the BatchLoader make sure generated files paths are correctly specified in **self.quora_data_files**.
Also replace **self.glove_path** with your local glove. 

To run try command **python train.py --use-quora**. That will include quora files to the datasets used.

**Comment by SeekPoint** [comment]
the dataset is not avaiable anymore

**Comment by SeekPoint** [comment]
get it from kaggle

**Comment by SeekPoint** [comment]
I got the data from kaggle:
ub16hp@UB16HP:~/ub16_prj/paraphrases-generator$ unzip question-pairs-dataset.zip 
Archive:  question-pairs-dataset.zip
  inflating: questions.csv           
ub16hp@UB16HP:~/ub16_prj/paraphrases-generator$ 

and I replace quora_duplicate_questions.tsv with questions.csv     
however, 

ub16hp@UB16HP:~/ub16_prj/paraphrases-generator$ python3 quora_data_process.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'is_duplicate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quora_data_process.py", line 29, in <module>
    Counter(df['is_duplicate'])
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'is_duplicate'
ub16hp@UB16HP:~/ub16_prj/paraphrases-generator$

**Comment by ale3otik** [comment]
'is_duplicate' is the name of label column for the old quora dataset. The paraphrases used are the only questions labeled with '1'(true). For the new dataset it might have different name. You should write your custom preprocessor that takes only positive labeled pairs and builds it into csv with 2 columns : [question1, question2]. 

Also file encoding might be different because it's dataset/OS specific. Consider to add 'encoding' parameter while reading/writing files. 

The code in this repo was used for academic purposes, not supposed to have one-click end-to-end run. To use it you need take care of datasets/embeddings/relative and absolute paths. 

Also the model was tested with pytorch 0.4.0 that might be incompatible with early/later versions.

**Comment by SeekPoint** [comment]
where to get the new quora dataset ?

**Comment by ale3otik** [comment]
> where to get the new quora dataset ?

https://www.kaggle.com/c/quora-question-pairs/data
Actually, here is the dataset I used. Also column names are the same. Make sure you read the data into pandas dataframe correctly. 
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html
